### ISSUE TITLE
angularjs2 support

### ISSUE THREAD

**Issue by angu2starter** [ocombe/angular-localForage#103]
Is there any roadmap in near future to upgrade the implementation to angularjs2. I am eagerly looking to integrate it with my angularjs2 project. Could you please suggest if there is a way to integrate the current release with my angularjs2 project.

**Comment by ocombe** [comment]
Hello,
the current implementation is not for angular 2 at all, but you can use localForage in angular 2 without any need for a wrapper (like we did in angular 1).

**Comment by angu2starter** [comment]
If possible could you please provide some sample integration with angularjs2

**Comment by scotttrinh** [comment]
I imagine you'd want an RxJS wrapper for localForage since most ng2 apps seem to take that route. Is that true? If so, that's a totally separate effort, but doesn't sound too hard to implement in your app, or as a separate library.
