### ISSUE TITLE
Method defineDriver

### ISSUE THREAD

**Issue by tenorok** [ocombe/angular-localForage#105]
Hello and thank you for good project!

In the localForage appeared method `defineDriver`: https://mozilla.github.io/localForage/#custom-driver-api-definedriver
That would be fine to support the same method.

**Comment by scotttrinh** [comment]
I'll take a look into what this would take to implement. Always down for suggestions that bring us into parity with upstream.

**Comment by scotttrinh** [comment]
@tenorok 
It looks like you could accomplish this by grabbing the underlying instance and running `defineDriver` on that instance, like:

```js
var lf = $localForage.instance('instanceName');
lf.defineDriver(myCustomDriverObject);
```

We could provide a method directly on the $localForage service to do this, but I wanted to see what you thought of that solution. Would documenting this be enough for your use case, or should we add the helper method and just define a throw away instance just to define the driver?

**Comment by tenorok** [comment]
@scotttrinh oh, exactly! I did't think about it. It's just what I need, thank you.
I don't know about benefit from providing method to the service, may be you have opinion about API consistency?
Current issue can be considered as fixed for me :-)

**Comment by scotttrinh** [comment]
I think there is some value in having API consistency with upstream, so I'll leave it open for now. PR welcome on this, but I'll skip it for the `1.3.0` release. In the meantime, I'll add some documentation around this.
