### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by frlinw** [ocombe/angular-localForage#108]
Just a lil thing, localforage can support multi stores for indexeddb (a base feature...) since 1.3, is it possible to update angular-localForage dependencies ?
Next users will save a lot of time^^

Thanks

**Comment by frlinw** [comment]
Anyway, if we can't get an instance with name + storeName, the update is useless

**Comment by barryvdh** [comment]
Is there any ETA for localforage 1.4 support?

**Comment by ocombe** [comment]
Not really, if you want to make a PR you can, but I don't work on this lib anymore...

**Comment by barryvdh** [comment]
Ok sure, I don't see any breaking issues, so not sure why it wouldn't work. But should run some tests.

**Comment by barryvdh** [comment]
Okay so package.json was already updated. Submitted PR in #109 to also bump bower.json

**Comment by scotttrinh** [comment]
Thanks @barryvdh, I'm putting this as priority number one in my roadmap. Leaving this open until it's fully resolved.
