### ISSUE TITLE
New maintainer?

### ISSUE THREAD

**Issue by scotttrinh** [ocombe/angular-localForage#114]
@ocombe I know you mentioned in another issue that you were no longer working on this library. Do you have any qualms about bringing in a new maintainer or two? This is a very useful wrapper around a very useful library, so I'd hate to see it languish, or for people to pass it by if it grows stale.

**Comment by ocombe** [comment]
Sure, if anyone wants to take over, I don't mind at all, it would be a good
thing. Are you interested?

**Comment by scotttrinh** [comment]
I'd be happy to take over the responsibility. Feel free to email me directly, and we can talk about the logistics. scott@scotttrinh.com

**Comment by mackelito** [comment]
Did this ever happened? :)

**Comment by scotttrinh** [comment]
@mackelito Yeah, I've been taking on most of the responsibility of triaging issues and making releases.

**Comment by mackelito** [comment]
Ok cool.. just wanted to know if development stopped or not 👍

**Comment by scotttrinh** [comment]
Alive and well! Pretty stable at this point, but there are a few proposed feature changes in the works and some more documentation.
