### ISSUE TITLE
import/require should return module name

### ISSUE THREAD

**Issue by zaalbarxx** [ocombe/angular-localForage#125]
Hi!
Like I explained in description if I import the module like `import angularLocalForage from 'angular-localforage';` I believe the module should be returned to me so I can then pass it as dependency to my module like `angularLocalForage.name`.

**Comment by scotttrinh** [comment]
I agree 100%.

**Comment by scotttrinh** [comment]
@zaalbarxx It looks like [we're already doing this](https://github.com/ocombe/angular-localForage/blob/master/dist/angular-localForage.js#L496). You can import like this:

```js
import angularLocalForage from 'angular-localforage';

angular.module('myModule', [ angularLocalForage ]);
```

If you run into any problems, feel free to reopen the issue and let us know what you find!

**Comment by zaalbarxx** [comment]
The problem exists in Webpack where instead of going the `module.exports` path it actually uses `define` which does not return anything. Maybe the if order should be changed so the Node syntax should be checked first `typeof exports`.

**Comment by scotttrinh** [comment]
I'll take a PR on this if you want to find a better UMD template that still supports other build tools (rollup, browserify, etc.)

**Comment by zaalbarxx** [comment]
The only thing that actually needs to be done is to add `return`  to 
``if(typeof define === 'function' && define.amd) {                    // AMD
    define(['localforage'], function(localforage) {
      return factory(angular, localforage);
    });
  }
``

**Comment by zaalbarxx** [comment]
Could you also create new release for this merge ? :)
