### ISSUE TITLE
Change dependencies from dist to source?

### ISSUE THREAD

**Issue by mackelito** [ocombe/angular-localForage#130]
Not really sure why I get this notice:
```
Critical dependencies:
7:484-491 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/localforage/dist/localforage.js 7:484-491
```

What do I need to change?

**Comment by scotttrinh** [comment]
Are you using a bower plugin with `webpack`? [See this similar issue from reflux.](https://github.com/reflux/refluxjs/issues/283)

**Comment by mackelito** [comment]
Nope.. just using npm (yarn) with webpack :)
Could it be related to
```
  "main": "dist/angular-localForage.js",
```
in package.json ?

**Comment by scotttrinh** [comment]
Could be, but honestly, this module is written as a single file anyway, so I'm not sure that you wouldn't still get that same message. Feel free to change it in your local `node_modules` folder and see if you still get that error. If you do, ¯\_(ツ)_/¯. If not, I'm not sure I'm comfortable with changing it without testing out the other popular build systems (browserify, rollup, closure) first. Let me know what you find out, and feel free to submit a PR.

**Comment by scotttrinh** [comment]
Closing this, but please reopen if you need additional help or have anything else to add.
