### ISSUE TITLE
Storing huge object freeze my app

### ISSUE THREAD

**Issue by Adavo** [ocombe/angular-localForage#133]
Hello,

I have to store a huge object into my IndexedDb, on background task. 
Before I used the IndexedDB pure api (no lib) and I had no issue.

But since I use localforage and angular-localforage, the UI doesn't respond (seems the app is frozen) until the storing is finished.

Is it possible that angular-localForage block the digest of angular during a save?

Edit: I store json.stringify and it's much faster... I suppose that is a good practice to stringify huge object...
Thanks for your help.

**Comment by scotttrinh** [comment]
@Adavo I don't think you should have to stringify your object to get good performance. I'll take a look. Do you have a sense of just how big the object is? Could you share the code you're using that seems to be causing the blocking?

**Comment by scotttrinh** [comment]
I think I see the performance issue: https://github.com/ocombe/angular-localForage/blob/master/src/angular-localForage.js#L125

We're copying the whole object in order to remove `$promise` if it's present. Seems like we can do something smarter here and get a huge performance boost for large object storage. I'll put something together and let you know. In the meantime, if you can get by with stringifying and parsing your object that'll do.

Thanks for bringing this up! Can't wait to fix this for my own purposes, too.

**Comment by Adavo** [comment]
Hello :-)
Didn't expect a so quick answer.
I store a dictionary of word so yes is massive but not that much (around 15mb) .
Stringify didn't work that's why it was so fast ha ha.
I think indeed for an object or array of object is super slow and as far as I remember I tried on 5mo blob content and it was ok.
Indeed I quickly look the code and saw this line. Nice catch.
If you have an idea of the fix or if you fix it I can try tomorrow (utc+8 for me now so...)

21 févr. 2017 22:15 wrote on Scott Trinh <notifications@github.com>:

I think I see the performance issue: https://github.com/ocombe/angular-localForage/blob/master/src/angular-localForage.js#L125

We're copying the whole object in order to remove $promise if it's present. Seems like we can do something smarter here and get a huge performance boost for large object storage. I'll put something together and let you know. In the meantime, if you can get by with stringifying and parsing your object that'll do.

Thanks for bringing this up! Can't wait to fix this for my own purposes, too.

**Comment by scotttrinh** [comment]
I have an idea, but it'll probably be a day or two before I have tests written, a fix implemented and a new version published. If you're cool the hang out for a few days while that gets patched, I'll just let you know when it's fixed.

**Comment by Adavo** [comment]
Now, I store the big object as a blob and it's very efficient. I will continue with that solution but still interesting to know when this performance issue is fixed ;-)

**Comment by scotttrinh** [comment]
@Adavo 

Glad blob storage ended up being a good optimization for you. I've fixed the copying issue, do you mind trying it out with the new version (1.4.4) and tell me if that works better than before?

**Comment by Adavo** [comment]
OK let me try tomorrow and I will tell you if it's better.

22 févr. 2017 9:31 PM wrote on Scott Trinh <notifications@github.com>:

@Adavo<https://github.com/Adavo>

Glad blob storage ended up being a good optimization for you. I've fixed the copying issue, do you mind trying it out with the new version (1.4.4) and tell me if that works better than before?

**Comment by Adavo** [comment]
I was so curious that I couldn't wait tomorrow.
Good point, saving the whole object is faster than before, which prevent the app to freeze a long time (instead of freezing like 6sec is more like 2sec, which is quite impressive). 
It's similar to blob so I think this bug is "fixed" ;-)

For reference, my object is an array of 114328 objects like this one:
{
frequency: 7
hanzi:"干"
isNew:false
pinyin:"gān"
translations: {
    en-US:"old variant of 干[gān]"
   }
}

As I still have like 2sec of latency, I may try if time to use a service worker to avoid DOM freeze. Maybe the lib can manage this by itself, one day ... ;-)

**Comment by scotttrinh** [comment]
@Adavo 

Excellent, I'm glad that gave you performance comparable to storing a blob! I'd be interested in using Web Workers to keep from blocking the main thread, so stay tuned.
