### ISSUE TITLE
Facebook In-App Browser

### ISSUE THREAD

**Issue by crascher** [ocombe/angular-localForage#135]
Hi does the lib work with facebook in-app browser from the Facebook App for iOS?

I have a problem that my app stops after localForage.setItem for:
Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Mobile/14D27 [FBAN/FBIOS;FBAV/78.0.0.40.70;FBBV/48784289;FBRV/0;FBDV/iPhone9,3;FBMD/iPhone;FBSN/iOS;FBSV/10.2.1;FBSS/2;FBCR/3Austria;FBID/phone;FBLC/de_DE;FBOP/5]

**Comment by scotttrinh** [comment]
Hey @crascher!

Honestly, I'm not sure. Since this is just a thin wrapper around [localForage](https://github.com/localForage/localForage), this might be a more appropriate question for them. If they support it, but for some reason this wrapper causes problems, I'd be happy to dig into with/for you and see if we can get it going.

Link to this issue when you open an issue with localForage, and I'll keep an eye on your conversation over there and help out where I can.

**Comment by crascher** [comment]
Thanks for the quick reply, issue open for localForage: https://github.com/localForage/localForage/issues/670

**Comment by scotttrinh** [comment]
Just thought of a simple test you can try to see if it's the wrapper or the library:

```js
$localForage
  .instance()
  .setItem('test', yourTestData)
  .then(function () {
    // If you get here, localForage works, and there might be something in angular-localForage that is failing
  });
```

This gets the underlying `localForage` instance and performs the `setItem` directly on that instead of passing through our `setItem` wrapper method.

**Comment by crascher** [comment]
@scotttrinh I tested with this code, unfortunately its not going in the then function when I run it in the Facebook In-App Browser. Can I turn on or catch somehow advanced error logging?

**Comment by scotttrinh** [comment]
Yeah, this stuff returns a `Promise` so you can:

```js
$localForage
  .instance()
  .setItem('test', yourTestData)
  .then(function () {
    // If you get here, localForage works, and there might be something in angular-localForage that is failing
  })
  .catch(function (e) {
    console.error(e) // or whatever
  });
```

**Comment by scotttrinh** [comment]
Closing since I haven't heard anything back from you on this issue, but feel free to re-open if you have anything else to add or if you still need help with this.
