### ISSUE TITLE
Could not make the example work 

### ISSUE THREAD

**Issue by sherwincode** [ocombe/angular-localForage#52]
A newbie here. Have installed angular-localForage through node.js, and redirect all the script files to the right path. Couldn't get the save button to save input value to local storage. 

Use console.log() to debug. No errors shown when load up the page and angular should be working. But console.log() stop working right after $localForage.setItem(...). 

I have also tried the examples from the Mozila-localForage and that one works just fine. I didn't change a thing except for reseting the path for script files, no idea what is wrong...

**Comment by ocombe** [comment]
Hmm do you have an error log ?
Did you include the lib localforage before angular-localForage ?

**Comment by sherwincode** [comment]
I didn't get a err log(), just the console.log() suppose to return a value, 

console.log(data) returns value in the console, while console.log($scope.myTest) is not triggered at all.

```
$scope.store = function(data) {
        console.log(data);
		$localForage.setItem('myTextStored', data).then(function(data) {
			$scope.myText = '';
            console.log($scope.myTest);
			$scope.myTextStored = data;
		});
	};
```
I did have include the lib localforage before angular-localForage.

**Comment by ocombe** [comment]
Ok so the promise is not resolve, are you calling $scope.store somewhere outside the scope ? In a non angular event for example ? In which case you will need to do a $scope.$apply

**Comment by sherwincode** [comment]
Here is the files, I would really appreciate if you can take a look. I don't think I have changed anything from the original example files.

html
```
<!doctype html>
<html ng-app="myApp">
<head>
    <meta charset="UTF-8">
    <title>Angular localForage example</title>
  
</head>
<body ng-controller="MyCtrl">
        Manual store: <input ng-model="myText">
        <button ng-click="store(myText)">Save</button>

        <div class="ng-cloak">Stored value: {{ myTextStored }}</div>
    
    
    <script src="node_modules/angular-localforage/bower_components/angular/angular.js"></script>
    <script src="node_modules/angular-localforage/bower_components/localforage/src/localforage.js"></script>
    <script src="node_modules/angular-localforage/dist/angular-localForage.js"></script>
    <script src="app.js"></script>
    <script src="controller.js"></script>
        
</body>
</html>

```

app.js
```
'use strict';

// Declare app level module which depends on filters, and services
var app = angular.module('myApp', ['LocalForageModule']).config(['$localForageProvider', function($localForageProvider) {
	$localForageProvider.config({
		name: 'myApp' // name of the database and prefix for your data
	});
}]);

```

controller.js
```
'use strict';

/* Controllers */

app.controller('MyCtrl', ['$scope', '$localForage', function ($scope, $localForage) {


    $scope.store = function(data) {
       console.log (data); // for debug
        $localForage.setItem('myTextStored', data, function (data) {
            $scope.myText = '';
            console.log ($scope.myText); // for debug
			$scope.myTextStored = data;
            console.log($scope.myTextStored); //for debug
		});
	};
    
}]);

```

**Comment by ocombe** [comment]
Ok I found your problem, you are using "bower_components/localforage/src/localforage.js" when you should be using "bower_components/localforage/dist/localforage.js" 
The src file of the localforage library is not complete, you need to append the drivers (that's why there is a dist file) :)

**Comment by sherwincode** [comment]
I see. Thanks for the answer.
