### ISSUE TITLE
How to set up incremental key?

### ISSUE THREAD

**Issue by sherwincode** [ocombe/angular-localForage#53]
It is not actually an issue. But I don't know where to ask a question like this.  In javascript (indexedDB), one can use an objectstore.app() function to store value into a key, which is incremental automatically. like

key           value
0               {object1}
1               {object2}

The setitem() function in localForage could not accomplish this. Is there a simple function I can use to  make that happen, or I have to use service to setup a logic?

Thanks.

**Comment by ocombe** [comment]
You will have to make it yourself, sorry :)

**Comment by sherwincode** [comment]
Can I use this to fetch the number of keys in the storage?

```
   $localForage.length().then(function(data){
            var keylength = data;
       });
```

**Comment by sherwincode** [comment]
I was trying to get the length of the db and use the key = length +1 to setup the new key for the next data entry. I manage to make it work by using the following codes. It seems the setItem function have to live within the length() function to make it work. 

```
// the way that won work
$scope.add = function() {
       $localForage.length().then(function(data){
           var keylength = data; 
       });
      $localForage.setItem(service.keyvalue(keylength), $scope.movie).then(function() {
               $location.path('/tab/dash');       // once a new data is stored, return to dash
		});
};
```

```
// the way that works
$scope.add = function() {
       $localForage.length().then(function(keylength){
           $localForage.setItem(service.keyvalue(keylength), $scope.movie).then(function() {
               $location.path('/tab/dash');       // once a new data is stored, return to dash
		});
       });
};
//in the factory

.factory('service', function(){
       return {
         keyvalue: function (keylength){
         var k= keylength+1;
         return k;
         }
    }
});

```

**Comment by ocombe** [comment]
Yes if you use an async database such as IndexedDB or WebSQL the length function will be async too anyway, I'm glad that you figured out how to do this.

**Comment by jumaris88** [comment]
But when you delete a item, you will get problem.
