### ISSUE TITLE
key path and auto increment 

### ISSUE THREAD

**Issue by sherwincode** [ocombe/angular-localForage#54]
Can I set up key path and auto increment by using localForage?

**Comment by ocombe** [comment]
There is no auto increment functionality for now. How would you like it to work?

**Comment by sherwincode** [comment]
The function I try to achieve is when inserting new entry into the database, for example

key = 1,
Content={
id: 1,
......
.....}.

This way, when using ng-repeat with #href, it is easier to circulate the array by looking at the object.id instead of a separate key. Once the id is found, the rest of the content could be located at the same object level. 

I originally pushed indexDb entries into an array without assigning specific id within the object. It made it real hard to use $stateparam to find the object content. 

I don't know if I made myself clear. I did managed to make it work right now, by manually insert object.id when storing the data into indexDb.
