### ISSUE TITLE
getItem returns undefined for un-found key (rather than null)

### ISSUE THREAD

**Issue by ericeslinger** [ocombe/angular-localForage#55]
The localForage documentation indicates that something like:

    localforage.getItem('foo').then(function(data) {
      console.log(data);
    });

should show data as `null`, if there's no key named 'foo' in the localForage storage systems.

The localforage library itself returns null in this case, but if I use the angular wrapper to call $localForage.getItem('foo'), the promise resolves with undefined instead of null. This is a little different from expected behavior, which made my `if (data === null)` code not quite detect key-not-found issues.

**Comment by ocombe** [comment]
Hey, you're right, I'm doing:

```js
deferred.resolve(item || res);
```

But in this case item is null, and res is undefined.
Thanks for the report, I'll fix it!

**Comment by rkriitr** [comment]
$localForage.getItem('brandChainNames', function(err, data) {
		    // The same code, but using ES6 Promises.
		    console.log('_storedValue: '+ data);
		});
There is no key so far (verified in tools-> storage perspective). But that console output does not print. Could someone tell me what could be the problem. console output before and after it prints fine.

**Comment by lordgreg** [comment]
For me, this isn't working at all for booleans or null-cased numbers:

Settings value to ```0, -1 or false``` with setItem always returns ```undefined``` with getItem.

**Comment by ocombe** [comment]
I haven't release a new version since this merge, are you using the master ?
