### ISSUE TITLE
Getting results in sync

### ISSUE THREAD

**Issue by paishin** [ocombe/angular-localForage#57]
Is there a way to get results in sync?

I am using the following factory
```
.factory('test', function($localForage) {
var data = [];
$localForage.getItem('data').then(function(result){ data = result;} )

return {
getData : return data;
}
}
```

unfortunately it always returns an empty dataset

**Comment by ocombe** [comment]
No, it's not possible because both indexedDB & WebSQL are async.
Besides it would defeat the purpose of this lib (provide an async system of storage, what ever storage type you use).

If you need your storage to be synchronous, you should use localstorage without any lib, it's really easy to use.

**Comment by paishin** [comment]
I am actually in the process of removing localstorage because i have exceeded the ios storage limitation. 

Could anyone suggest how you can create an angular factory using localforage?

**Comment by ocombe** [comment]
You might want to try using lz-compression of the data that you store: http://pieroxy.net/blog/pages/lz-string/index.html & https://github.com/pieroxy/lz-string/
You would save like 75-90% of storage (text is the easiest thing to compress).
