### ISSUE TITLE
Cannot use in ionic?

### ISSUE THREAD

**Issue by superandrew** [ocombe/angular-localForage#64]
I have added localForage and angular-localForage via bower.

When I launch the app with these dependencies:

    angular.module('<appname>', [
          'ionic',
          'config',
          'ngCordova',
          'uuid4',
          'LocalForageModule'
        ])`
I have the module dependency error:

    Error: [$injector:modulerr] Failed to instantiate module hsr001App due to:
     [$injector:modulerr] Failed to instantiate module LocalForageModule due to:
     [$injector:nomod] Module 'LocalForageModule' is not available!

I've tried with version 1.2.2 and 1.2.3, both are failing. Any Idea?

**Comment by ocombe** [comment]
Did you load the js file for localforage _before_ the application ?

**Comment by superandrew** [comment]
yes, I guess:

    <script src="lib/angular/angular.js"></script>
    <script src="lib/angular-animate/angular-animate.js"></script>
    <script src="lib/angular-sanitize/angular-sanitize.js"></script>
    <script src="lib/angular-ui-router/release/angular-ui-router.js"></script>
    <script src="lib/ionic/release/js/ionic.js"></script>
    <script src="lib/ionic/release/js/ionic-angular.js"></script>
    <script src="lib/ngCordova/dist/ng-cordova.js"></script>
    <script src="lib/ngImgCache/ngImgCache.js"></script>
    <script src="lib/angular-resource/angular-resource.js"></script>
    <script src="lib/angular-cookies/angular-cookies.js"></script>
    <script src="lib/angular-cached-resource/angular-cached-resource.js"></script>
    <script src="lib/angular-uuid4/angular-uuid4.js"></script>
    <script src="lib/localforage/dist/localforage.js"></script>
    <script src="lib/angular-localForage/dist/angular-localForage.js"></script>
    
    



    
    
    <script src="scripts/app.js"></script>
    <script src="scripts/controllers.js"></script>

**Comment by superandrew** [comment]
I see this error with version1.2.0
   
    Error: Mismatched anonymous define() module: function (localforage) {
      factory(root.angular, localforage);
    }
    http://requirejs.org/docs/errors.html#mismatch

**Comment by ocombe** [comment]
Ah this looks like a bug with requirejs, does the ionic packager use requirejs ?
Any chance you could send me a minimal test case ?

**Comment by superandrew** [comment]
just sent it at your email, thank you very much!

**Comment by ocombe** [comment]
Ok, the problem is that localforage has added the support for requirejs, and uses localforage as its name, and my lib uses the same name.
I have to change it to angular-localforage so that it doesn't try to redefine the name !
Thanks for the report :)

**Comment by superandrew** [comment]
Nice to hear that. Is there any way I could use it patching the sources or using a previous version?

Thanks!

**Comment by ocombe** [comment]
Sure I'll send you the fixed code by mail once I've found a better way to do it

**Comment by ocombe** [comment]
oh wait I was wrong, just comment the line 24 in index.html

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.9/require.min.js"></script>
```

This is what is causing the conflict...

**Comment by ocombe** [comment]
explanation: if you include requirejs, you need to load your libs using requirejs, otherwhise they will conflict with the define function from requirejs

**Comment by superandrew** [comment]
Thank you so much! I don't know require very well, I forgot I included there following the LightStreamer tutorial, so when it got loaded from a bower dependency it must have provoked a mess :)

:8ball:

**Comment by ocombe** [comment]
Yeah I'm not a big requirejs fan either, I find it overly complicated :)
