### ISSUE TITLE
iterate with iterationNumber

### ISSUE THREAD

**Issue by eMerzh** [ocombe/angular-localForage#78]
In localforage, the iterate function contains an iteration number, 
it can be handy and it shouldn't be that hard to add ...no?

https://mozilla.github.io/localForage/#iterate

Thanks

**Comment by scotttrinh** [comment]
Agreed. It should be API-compatible with localForage. Thanks for spotting it!

**Comment by scotttrinh** [comment]
@eMerzh 
I looked into this a bit, and it seems like a documentation issue, as we just pass the callback directly to `localForage`, which should pass the same values to your callback as the unwrapped version. I'll write some unit tests and documentation.
