### ISSUE TITLE
Directives requests data before done storing

### ISSUE THREAD

**Issue by mackelito** [ocombe/angular-localForage#83]
When I load the app, my directives are requesting data from localstorage before it's stored.

This is done in the .run part.

    // Get names and save in localStorage
    $http.get('js/data.json').then(function(res) {
      $localForage.setItem('test', res.data).then(function(res) {
        console.log('Store data in localStorage');
        console.log(res);
      });
    });

Then I just request it in my directive

    $localForage.getItem('data').then(function(data) {
        console.log('Get All Data');
        //console.log(data);
        vm.data = data;
      });

On first load the directive has no data.. but on refresh the data is there.. 
Ideas?

**Comment by gabe0x02** [comment]
Makes sense to me.  You have to put some logic that waits for the write before you can read anything.  In fact if the data changes on the server I'm sure you probably get stale data in your directive unless you refresh again.  Maybe your directive should be doing your get from the network and only local storage if that fails.

**Comment by mackelito** [comment]
I moved this to be resolved by ui-router and it works as needed.. 
In my case the data will not change there for there is no need to ever load from the server again ;)
