### ISSUE TITLE
Update the localForage version

### ISSUE THREAD

**Issue by yorchv** [ocombe/angular-localForage#84]
Please update the localForage requirement to ~1.2.10 to remove dependency conflicts when using bower.

**Comment by futbotism** [comment]
+1

**Comment by aviraldg** [comment]
:+1:

**Comment by ocombe** [comment]
Done, sorry for that :)

**Comment by futbotism** [comment]
Is it possible to bump the bower.json localforage dependency to 1.2.10 also?

**Comment by ocombe** [comment]
Yes sorry, done
