### ISSUE TITLE
Empty error message on eReader

### ISSUE THREAD

**Issue by seblucas** [ocombe/angular-localForage#95]
Hi,

First thanks for this great tool. I'm using it for quite some time and I recently had an issue on the embedded browser of a Kobo eReader. It's supposed to be using webkit and for some reason the driver it use is WebSQL. The real problem I have is the each time I do a getItem, the promise always fail with an empty error message. Strange isn't it ?

Do I need to make a test with localforage only (no angular), is there a chance that I get a better error message ?

Thanks in advance.

**Comment by ocombe** [comment]
You can try yes, but I'm not sure that the message will be different :)

**Comment by seblucas** [comment]
That's what I thought, but a lazy guy has to try ;)

Judging from your code, the chance is slim.

Thanks.
