### ISSUE TITLE
Unable to catch errors if there is no available storage method

### ISSUE THREAD

**Issue by rromanw** [ocombe/angular-localForage#96]
It may happen that in certain cases the browser is unable to open the database. This happens for example with firefox with indexeddb when there is not enough space on the disk. Under such circumstances, localforage produces some errors and there doesn't seem to be a way to catch them.

Suppose following code:
```javascript
localforage.config({
  name: 'somestorage',
  // Let's pretend that no storage is available. 
  // The real world situation would be [localforage.INDEXEDDB] with firefox
  // without space on the disk.
  driver: []  
});

localforage.getItem('foo',function(err,val){
  console.debug('handler1',err,val);
}).catch(function(err) {
  console.debug('catch1!',err);
});

localforage.getItem('foo',function(err,val){
  console.debug('handler2',err,val);
}).catch(function(err) {
  console.debug('catch2!',err);
});
```
Under these circumstances, the console output is this:
```
catch1!
catch2!
Error: Driver not found. // When we are in the Firefox IndexedDB full disk scenario, we get QuotaExceededError
Error: No available storage method found. (4*)
```

One problem is, that the handler functions don't get called at all, the second problem is that those errors cannot be caught and silenced. Is this intended behaviour?

**Comment by ocombe** [comment]
It is not intended, but there is no way around it, unfortunately those errors ain't catchable (I don't know why, but believe me I tried)... :(
If you ever find a way around it, let me know.
