### ISSUE TITLE
Angular 2.0

### ISSUE THREAD

**Issue by jernejc** [ocombe/angular-localForage#98]
Is Angular 2.0 on the roadmap for the near future?

**Comment by ocombe** [comment]
You don't really need a wrapper for Angular 2, it should work with localforage :)

**Comment by jernejc** [comment]
I was mostly thinking about the bind functionalities, but I guess that doesn't really make sense without $scope.

Thanks for the quick info

**Comment by ocombe** [comment]
No prob.
I don't think it would be really hard to bind with angular 2.
